function data=corrDivRate(data,cExperiment,timerange)
%Correlates number of cell divisions within a range of timepoints with
%median expression level in cells having defined birth events

%data is generated by extractDandruffData.m
%cExperiment should have a .cellInf field populated with data from a
%fluorescence channel
%Timerange is a 2 element vector representing the starting and ending
%timepoints

fieldName=[num2str(timerange(1)) 'to' num2str(timerange(2))];
%Loop through the cells
for c=1:length(data.motherIndices)
    data.median(c)=cExperiment.cellInf(1).median(data.motherIndices(c));
    data.(['births' fieldName])(c)=data.cumsumBirths(c,timerange(2))-data.cumsumBirths(c,timerange(1));    
end